export const FEATURE_FLAGS = {
  AUTO_ACCESS_REVOCATION: false,
  HEARTBEAT_REVALIDATION: false,
  PREMIUM_DEVICE_ENFORCEMENT: true,
  PREMIUM_SESSION_MONITORING: true,
  DEFAULT_MAX_SESSIONS_USER: 3,
  DEFAULT_MAX_SESSIONS_ADMIN: 3,
  DROPDOWN_MAX_LIMIT: 3
};
